import SwiftUI
import UniformTypeIdentifiers

/// macOS keeps import as one visible workbench: intake/status, row spine, and
/// selected-row inspector remain side by side rather than becoming a web table.
public struct V15StatementImportMacView: View {
    @Environment(\.scenePhase) private var scenePhase
    @State private var model: V15StatementImportModel
    @State private var importer = false
    @State private var selectedID: UUID?
    @State private var confirmation = false
    private let initialGalleryScenario: String?
    public init(services: V15Services, offlineSnapshotAt: Date? = nil, initialGalleryScenario: String? = nil) { _model = State(initialValue: V15StatementImportModel(services: services, offlineSnapshotAt: offlineSnapshotAt)); _selectedID = State(initialValue: nil); self.initialGalleryScenario = initialGalleryScenario }
    public var body: some View { HStack(spacing: 0) { intake.frame(minWidth: 230, idealWidth: 250, maxWidth: 300); Divider(); rowSpine.frame(minWidth: 390, maxWidth: .infinity); Divider(); inspector.frame(minWidth: 280, idealWidth: 320, maxWidth: 360) }
        .background(V15Palette.paper.color)
        .accessibilityElement(children: .contain)
        .fileImporter(isPresented: $importer, allowedContentTypes: [.pdf], allowsMultipleSelection: false) { result in if case .success(let urls) = result, let url = urls.first { model.selectFile(url: url) } }
        .sheet(isPresented: $confirmation, onDismiss: { model.dismissPreview() }) { confirmationSheet.frame(minWidth: 460, minHeight: 340) }
        .task { if model.batch == nil, let initialGalleryScenario { await model.prepareSyntheticGallery(initialGalleryScenario); selectedID = model.workbench?.rows.first?.id; if ["statement-import-preview", "statement-import-preview-error", "statement-import-preview-conflict"].contains(initialGalleryScenario) { confirmation = true } } }
        .onChange(of: scenePhase) { _, phase in if phase != .active, initialGalleryScenario == nil { model.sceneDidLeaveActive() } }
        .onDisappear { model.sceneDidLeaveActive() }
        .accessibilityIdentifier("v15.f3g.statement-import.macos") }
    private var intake: some View { VStack(alignment: .leading, spacing: V15Spacing.md) { Text("账单导入").font(V15Typography.surfaceTitle); Text("本地脱敏 · 人工确认").font(V15Typography.secondary); Button("选择 PDF") { importer = true }.accessibilityIdentifier("v15.f3g.mac.pick-file").disabled(!model.writeReasons.isEmpty); Divider(); if let board = model.workbench { Label(board.status.displayName, systemImage: "doc.text").accessibilityIdentifier("v15.f3g.mac.status") } else if let batch = model.batch { Label(batch.status.displayName, systemImage: "doc.text").accessibilityIdentifier("v15.f3g.mac.status") }; if case .awaitingProviderConsent = model.phase { Toggle("确认仅发送脱敏证据", isOn: $model.providerAuthorized).accessibilityIdentifier("v15.f3g.mac.provider-consent"); Text("execution_scope=request_bound").font(V15Typography.secondary); Button("请求内解析") { model.requestProviderAttempt() }.disabled(!model.providerAuthorized || !model.writeReasons.isEmpty) } else if case .providerResponseUnknown = model.phase { Text("解析结果未知；同一凭证恢复。 ").font(V15Typography.secondary); Button("恢复解析") { model.requestProviderRecovery() }.accessibilityIdentifier("v15.f3g.mac.provider-recover").disabled(model.writeReasons.contains(where: { $0.code == "unknown_import_status" })) } else if case .reviewing = model.phase { Button("运行校验") { model.requestValidation() }.accessibilityIdentifier("v15.f3g.mac.validation").disabled(!model.writeReasons.isEmpty) }; if let snapshot = model.offlineSnapshotAt { V15OfflineReadOnlyBanner(snapshotAt: snapshot) }; Spacer() }.padding(V15Spacing.md).frame(minWidth: 230).accessibilityElement(children: .contain).accessibilityIdentifier("v15.f3g.mac.intake") }
    private var rowSpine: some View { VStack(alignment: .leading, spacing: 0) { HStack { Text("复核行").font(V15Typography.surfaceTitle); Spacer(); Button("刷新") { model.requestReloadWorkbench() } }.padding(V15Spacing.md); Picker("来源", selection: Binding(get: { model.workbenchFilter.evidenceState ?? "all" }, set: { model.requestWorkbenchEvidenceFilter($0 == "all" ? nil : $0) })) { Text("全部").tag("all"); Text("可用").tag("available"); Text("不可用").tag("unavailable") }.pickerStyle(.segmented).padding(.horizontal, V15Spacing.md).accessibilityIdentifier("v15.f3g.mac.filter"); if let message = model.resolutionReadbackMessage { Text(message).font(V15Typography.secondary).padding(.horizontal, V15Spacing.md).accessibilityIdentifier("v15.f3g.mac.resolution-readback-status") }; if model.isResolutionReadbackInFlight { ProgressView("正在读取完整复核行…").padding(.horizontal, V15Spacing.md).accessibilityIdentifier("v15.f3g.mac.resolution-readback-loading") }; if case .failed(let failure) = model.phase, failure.code == "resolution_response_unknown" { V15ServiceErrorState(message: failure.message, retryIdentifier: "v15.f3g.mac.resolution-readback-retry", retry: { model.retryFromFailure() }).padding(.horizontal, V15Spacing.md).accessibilityIdentifier("v15.f3g.mac.resolution-readback-error") }; Divider(); if let board = model.workbench { if board.sourceUnavailableCount > 0 { Text("不可用来源 \(board.sourceUnavailableCount) 页").font(V15Typography.secondary).padding([.horizontal, .top], V15Spacing.md).accessibilityIdentifier("v15.f3g.mac.source-unavailable") }; List(selection: $selectedID) { ForEach(board.rows) { row in HStack { Image(systemName: model.selectedRowIDs.contains(row.id) ? "checkmark.circle.fill" : "circle"); VStack(alignment: .leading) { Text("第 \(row.rowNumber) 行"); Text(row.draft?.resolution.displayName ?? "未处理").font(V15Typography.secondary) } }.tag(row.id).accessibilityIdentifier("v15.f3g.mac.row.\(row.id)").contextMenu { Button("加入/移出确认") { model.toggleRow(row.id) }.disabled(!model.writeReasons.isEmpty) } } }.accessibilityIdentifier("v15.f3g.mac.rows"); if board.nextCursor != nil { Button(model.isLoadingMore ? "正在加载…" : "加载更多") { model.requestNextWorkbench() }.padding(V15Spacing.md).accessibilityIdentifier("v15.f3g.mac.load-next").disabled(model.isLoadingMore) }; if let failure = model.workbenchFailure { V15ServiceErrorState(message: failure.message, retry: { model.requestReloadWorkbench() }).accessibilityIdentifier("v15.f3g.mac.workbench-error") } } else { Spacer(); if case .failed(let failure) = model.phase { V15ServiceErrorState(message: failure.message, retry: { model.retryFromFailure() }) } else { V15LoadingSkeleton() }; Spacer() } }.accessibilityElement(children: .contain).accessibilityIdentifier("v15.f3g.mac.workbench") }
    @ViewBuilder private var inspector: some View { VStack(alignment: .leading, spacing: V15Spacing.md) { Text("检查器").font(V15Typography.surfaceTitle); if let row = model.workbench?.rows.first(where: { $0.id == (selectedID ?? model.selectedRowIDs.first) }) { Text(row.evidenceTextMasked ?? "来源不可用").font(V15Typography.body); Text("候选 \(row.candidates.count) 个 · 行版本 \(row.rowVersion)").font(V15Typography.secondary); if row.draft?.resolution.isExecutable != true { Button("设为新建流水") { model.requestResolution(row: row, as: .createNew) }.disabled(!model.writeReasons.isEmpty); Button("忽略该行") { model.requestResolution(row: row, as: .ignoreIntentional) }.disabled(!model.writeReasons.isEmpty) }; Button(model.selectedRowIDs.contains(row.id) ? "移出确认" : "加入确认") { model.toggleRow(row.id) }.disabled(!model.writeReasons.isEmpty) } else { Text("选择一行以查看脱敏证据、候选与版本。 ").font(V15Typography.secondary) }; Button(model.isLoadingPage ? "正在读取脱敏页面…" : "查看脱敏页面") { model.requestPage(1) }.accessibilityIdentifier("v15.f3g.mac.page-load").disabled(model.isLoadingPage); if model.isLoadingPage { ProgressView("正在读取脱敏页面…").accessibilityIdentifier("v15.f3g.mac.page-loading") }; if let page = model.page { Divider(); Text("第 \(page.pageNumber) 页 · \(page.sourceAvailable ? "脱敏证据" : "来源不可用")").font(V15Typography.secondary); Text(page.evidenceTextMasked ?? "仅标准化位置框").font(V15Typography.body).accessibilityIdentifier("v15.f3g.mac.masked-page") }; if let failure = model.pageFailure { V15ServiceErrorState(message: failure.message, retryIdentifier: "v15.f3g.mac.page-retry", retry: { model.requestPage(1) }).accessibilityIdentifier("v15.f3g.mac.page-error") }; Divider(); Button("确认预览") { model.requestPreview(); confirmation = true }.accessibilityIdentifier("v15.f3g.mac.preview").disabled(!model.previewReasons.isEmpty); if let receipt = model.receipt { Text("\(receipt.status) · 新建 \(receipt.createdCount)").accessibilityIdentifier("v15.f3g.mac.receipt") }; if case .responseUnknown = model.phase { Text("确认结果未知；不会重发。 ").font(V15Typography.secondary); Button("读取同 key 收据") { model.requestReceiptReadback() }.accessibilityIdentifier("v15.f3g.mac.readback") }; Spacer() }.padding(V15Spacing.md).frame(minWidth: 280).accessibilityElement(children: .contain).accessibilityIdentifier("v15.f3g.mac.inspector") }
    private var confirmationSheet: some View { VStack(alignment: .leading, spacing: V15Spacing.md) {
        Text("服务器确认预览").font(V15Typography.surfaceTitle)
        if model.isPreviewLoading {
            ProgressView("正在获取服务器确认预览…")
            Text("正在获取服务器确认预览…").accessibilityIdentifier("v15.f3g.mac.preview-loading")
            Text("请保持当前页面；尚未创建流水。 ").font(V15Typography.secondary)
        } else if let failure = model.previewFailure {
            Text(failure.kind == .conflict ? "确认预览已过期" : "确认预览暂不可用").accessibilityIdentifier("v15.f3g.mac.preview-failure")
            Text(failure.message).font(V15Typography.body)
            Button("重试获取预览") { model.requestPreview() }.accessibilityIdentifier("v15.f3g.mac.preview-retry")
        } else if model.isConfirmationInFlight {
            ProgressView("正在创建流水…").accessibilityIdentifier("v15.f3g.mac.confirming")
            Text("请求已经提交；请勿重复确认。 ").font(V15Typography.secondary)
        } else if let receipt = model.receipt {
            Text("确认收据").font(V15Typography.surfaceTitle)
            Text("\(receipt.status) · 新建 \(receipt.createdCount) · 匹配 \(receipt.matchedCount) · 跳过 \(receipt.skippedCount)").accessibilityIdentifier("v15.f3g.mac.sheet-receipt")
        } else if case .responseUnknown = model.phase {
            Text("确认结果未知").accessibilityIdentifier("v15.f3g.mac.sheet-response-unknown")
            Text("不会盲目重发确认；关闭后仅可使用相同请求凭证读取收据。 ").font(V15Typography.body)
        } else if let preview = model.preview {
            Text("\(preview.counts.selected) 行 · 已知金额 ¥\(preview.amounts.knownTotalMinor / 100) · 未知来源 \(preview.amounts.unknownSelectedCount) 行")
            Text("将原样提交服务器返回的版本，不由客户端重建。 ").font(V15Typography.secondary)
            HStack { Button("取消") { confirmation = false }.disabled(model.isConfirmationInFlight); Spacer(); Button("确认创建") { model.requestConfirm() }.disabled(!model.confirmReasons.isEmpty).accessibilityIdentifier("v15.f3g.mac.confirm") }
        }
    }.padding(V15Spacing.lg).accessibilityIdentifier("v15.f3g.mac.confirmation") }
}
